version: "3"
services:

  fireapp:
    image: registry.gitlab.com/js-project-gis-1/js-fire-simulator-starter/fire-simulator:latest
    ports:
      - "8081:8081"
    depends_on: 
      - db_postgis 
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgis:5432/fire-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pssecret
    networks:
      - fire-network-private
      - fire-network-internal

  db_postgis:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pssecret
      APP_DB_NAME: fire-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - fire-network-private

  

networks:
  fire-network-private:
    internal: true
  fire-network-internal:
